name: modellll
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  intl:
  provider:
  http:
  get:
  get_storage:
  shared_preferences:
  cupertino_icons:
  toastify_flutter:
  liquid_glass_ui_design:
  liquid_glass_bottom_bar:
  tutorial_coach_mark: ^1.3.1
  supabase_flutter:
  remixicon: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/font/

  fonts:
    - family: Chillax
      fonts:
        - asset: assets/font/Chillax-Regular.ttf
        - asset: assets/font/Chillax-Bold.ttf
          weight: 700
        - asset: assets/font/Chillax-Light.ttf
          weight: 300
        - asset: assets/font/Chillax-Medium.ttf
          weight: 500
        - asset: assets/font/Chillax-Semibold.ttf
          weight: 600
